# s = set("HackerRank")
# print(s)
# print(s.intersection(set("Hacker")))
# print(s.intersection(set("Rank")))
# print(s.intersection(set(['R', 'a', 'n', 'k'])))
n = int(input())
my_set_1 = set(map(int, input().split()))
m = int(input())
my_set_2 = set(map(int, input().split()))
length = len(my_set_1.intersection(my_set_2))
print(length)